In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.3.0'

In [4]:
# DATA PREPROCESSING


In [5]:
dataset = pd.read_csv("D:\datasets\Churn_Modelling (1).csv")
X = dataset.iloc[:, 3 :-1].values
y = dataset.iloc[:, -1].values

In [6]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [8]:
print(y)

[1 0 1 ... 1 1 0]


In [ ]:
## Encoding Categorical data.

In [10]:
# Label encoding of Gender data.

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [11]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [14]:
# One hot encoding "Geograpgy" column.

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [15]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [16]:
## Splitting the dataset into Traiing and Test set

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 0)

In [18]:
## FEATURE SCALING.

In [20]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [21]:
## BUILDING THE ANN

In [22]:
#  Initialize the ANN

ann = tf.keras.models.Sequential()

In [23]:
# Adding the input layer and the first hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [24]:
# Adding the second hidden layer

ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [25]:
# Adding the output layer

ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [26]:
## TRAINING THE ANN.

In [29]:
# Compiling the ANN

ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [30]:
# Training the ANN on the Training set.

ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5704 - accuracy: 0.7234
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4642 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4416 - accuracy: 0.7968
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4290 - accuracy: 0.8081
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4200 - accuracy: 0.8176
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4116 - accuracy: 0.8232
Epoch 7/100
250/250 [==============================] - 0s 908us/step - loss: 0.4020 - accuracy: 0.8303
Epoch 8/100
250/250 [==============================] - 0s 888us/step - loss: 0.3928 - accuracy: 0.8349
Epoch 9/100
250/250 [==============================] - 0s 900us/step - loss: 0.3849 - accuracy: 0.8385
Epoch 10/100
250/250 [==============================] - 0s 884us/step - loss: 0.3779 

250/250 [==============================] - 0s 963us/step - loss: 0.3329 - accuracy: 0.8633
Epoch 81/100
250/250 [==============================] - 0s 949us/step - loss: 0.3325 - accuracy: 0.8641
Epoch 82/100
250/250 [==============================] - 0s 969us/step - loss: 0.3329 - accuracy: 0.8649
Epoch 83/100
250/250 [==============================] - 0s 962us/step - loss: 0.3325 - accuracy: 0.8644
Epoch 84/100
250/250 [==============================] - 0s 957us/step - loss: 0.3325 - accuracy: 0.8641
Epoch 85/100
250/250 [==============================] - 0s 973us/step - loss: 0.3328 - accuracy: 0.8650
Epoch 86/100
250/250 [==============================] - 0s 976us/step - loss: 0.3324 - accuracy: 0.8650
Epoch 87/100
250/250 [==============================] - 0s 949us/step - loss: 0.3326 - accuracy: 0.8643
Epoch 88/100
250/250 [==============================] - 0s 988us/step - loss: 0.3321 - accuracy: 0.8659
Epoch 89/100
250/250 [==============================] - 0s 946us/step - loss:

In [31]:
## Making predictions and evaluating the model

In [34]:
# predicting the result of single observation

print(ann.predict(sc.transform([[1 ,0 ,0 ,600 ,1 ,40 ,3 ,60000 ,2 ,1 ,1 ,50000]])) > 0.5)

[[False]]


In [39]:
# Predicting the Test set results

y_preds = ann.predict(X_test)
y_preds = (y_preds > 0.5)
print(np.concatenate((y_preds.reshape(len(y_preds),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [40]:
# Making a confusion Matrix

from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_preds)
print(cm)
accuracy_score(y_test, y_preds)

[[1521   74]
 [ 202  203]]


0.862